
CREATE TABLE LOGS (
    ID       NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MENSAGE  VARCHAR2(250) NOT NULL,
    FECHA    VARCHAR2(23)  NOT NULL
);
/

CREATE OR REPLACE PUBLIC SYNONYM CLIENTES FOR indra.LOGS;
GRANT SELECT, INSERT, UPDATE, DELETE ON indra.LOGS TO PUBLIC;
