--DROP TABLE TELEFONOS;
CREATE TABLE TELEFONOS (
    ID               NUMBER        PRIMARY KEY,
    NUMBERO          VARCHAR2(20)  NOT NULL,
    USUARIO          VARCHAR2(9)   NOT NULL,
    PROGRAMA         VARCHAR2(16)  NOT NULL,
    CREADO_POR       VARCHAR2(25)  NOT NULL,
    CREADO_EN        DATE          NOT NULL,
    ACTUALIZADO_POR  VARCHAR2(25),
    ACTUALIZADO_EN   DATE
);
/

CREATE OR REPLACE PUBLIC SYNONYM TELEFONOS FOR indra.TELEFONOS;
GRANT SELECT, INSERT, UPDATE, DELETE ON indra.TELEFONOS TO PUBLIC;