CREATE USER indra IDENTIFIED BY indra;

GRANT CONNECT, RESOURCE, DBA TO indra;

GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO indra;

GRANT UNLIMITED TABLESPACE TO indra;

-- GRANTS A TABLAS Y SQUEMAS ESPECIFICOS AQUI.
